name: Question Pipeline

on:
  # run every 8am utc
  schedule:
    - cron: '0 8 * * *'
  # allows me to run this workflow whenever i wanna, instead of always waiting for the schedule
  workflow_dispatch:

jobs:
  run-pipeline:
    # give a fresh new linux virtual machine to run on
    runs-on: ubuntu-latest
    # will do everything step by step like this
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # get all your hugging face models ( well all 3 of them ) + cache it
      - name: Cache Hugging Face models
        uses: actions/cache@v4
        with:
          path: ~/.cache/huggingface
          key: ${{ runner.os }}-huggingface-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      # after setting up the environment, run all these files now !!
      - name: Run fetch
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python3 -m src.loaders.db_loader

      - name: Run clean/dedup
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python3 -m src.transform.load_clean

      - name: Run classify
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python3 -m src.transform.classify
